import { actionableText } from "../domain/evidence-state";
import type { CentreEvidence } from "../application/get-centre-evidence";
import { EvidenceResolutionForm } from "./evidence-resolution-form";

const stateDescription = (state: string) => state === "not assessed yet" ? "Insufficient completed evidence." : state;
const filters = ["paper", "part", "vocabulary", "grammar", "spelling", "names", "numbers", "colours", "positions", "topic", "set"] as const;
const label = (key: string) => key === "set" ? "Practice set" : key[0]!.toUpperCase() + key.slice(1);
const timingValue = (value: unknown) => typeof value === "string" && value ? value : "Not recorded";

export function EvidenceDashboard({ evidence, learnerId, error, role }: { evidence?: CentreEvidence; learnerId?: string; error?: string; role: "teacher" | "academic_lead" | "admin" }) {
  const title = learnerId ? "Learner evidence detail" : "Centre evidence and actionable gaps";
  const filter = evidence?.filter ?? {};
  const current = new URLSearchParams(Object.entries(filter).map(([key, value]) => [key === "learnerId" ? "learner" : key === "practiceSetId" ? "set" : key, value]));
  if (error) return <section className="evidence-dashboard" aria-live="polite"><h1>{title}</h1><p>{error}</p><p><a className="account-link" href="/teacher">Return to centre evidence</a></p></section>;
  return <section className="evidence-dashboard" aria-live="polite">
    <p className="eyebrow">Staff evidence</p><h1>{title}</h1><p>Based on the latest submitted practice for each activity in the last 30 days.</p>
    <form className="evidence-filters" method="get"><input type="hidden" name="learner" value={learnerId ?? ""} />{filters.map((key) => <label key={key}>{label(key)}<input name={key} defaultValue={current.get(key) ?? ""} /></label>)}<button type="submit">Apply filters</button><a className="account-link" href={learnerId ? `/teacher?learner=${learnerId}` : "/teacher"}>Reset filters</a></form>
    {learnerId && <p><a className="account-link" href="/teacher">Return to centre evidence</a></p>}
    {!evidence || (!evidence.rows.length && !evidence.details.length) ? <><p><strong>State: not assessed yet</strong></p><p>No completed practice yet for this selection.</p></> : <>
      <div className="evidence-rows" role="list">{evidence.rows.map((row) => <article className="evidence-row" id={`learner-${row.learnerId}`} role="listitem" key={`${row.learnerId}-${row.paper}-${row.part}-${row.languageTarget}`}><h2>{row.learnerName}</h2><p>{row.paper.replace("_", " ")} Part {row.part} · {row.languageTarget}</p><p><strong>State: {stateDescription(row.state)}</strong></p><p>{actionableText(row.state, row.paper, row.part, row.languageTarget)}</p><p>{row.state === "not assessed yet" ? "Insufficient assessable outcomes." : `${row.correctOutcomes} correct from ${row.assessableOutcomes} assessable outcomes.`}</p>{!learnerId && <a className="account-link" href={`/teacher?${new URLSearchParams({ ...Object.fromEntries(current), learner: row.learnerId })}`} aria-label={`Open evidence detail for ${row.learnerName}`}>Open learner evidence detail</a>}</article>)}</div>
      <section className="evidence-details" aria-label="Submitted item detail"><h2>Submitted item detail</h2>{evidence.details.map((detail) => { const playback = detail.playback.filter((event) => event && event.itemId === detail.practiceSetItemId && typeof event.playedAt === "string"); const unresolved = detail.effectiveOutcome === "needs_teacher_review"; const canCorrect = detail.automaticOutcome === "needs_teacher_review" && role !== "teacher"; return <article className="evidence-detail" key={`${detail.reviewItemId}-${detail.languageTargetId}`}><h3>Submitted item</h3><p>{detail.learnerName} · {detail.paper.replace("_", " ")} Part {detail.part} · {detail.languageTarget} · Item {detail.position}</p><p>Response: {detail.responseLabel ?? (detail.response === null ? "No response" : String(detail.response))}</p><p>Automatic outcome: {detail.automaticOutcome.replaceAll("_", " ")}</p><p>Effective outcome: {detail.effectiveOutcome.replaceAll("_", " ")}{detail.resolutionRevision > 0 ? ` (resolution ${detail.resolutionRevision})` : ""}</p>{unresolved && <p><strong>Needs teacher review</strong></p>}{canCorrect && <EvidenceResolutionForm reviewItemId={detail.reviewItemId} revision={detail.resolutionRevision} outcome={detail.effectiveOutcome === "needs_teacher_review" ? "correct" : detail.effectiveOutcome} correction={detail.resolutionRevision > 0} />}<p>Started: {timingValue(detail.timing?.startedAt)} · Last saved: {timingValue(detail.timing?.lastSavedAt)} · Submitted: {timingValue(detail.timing?.submittedAt)}</p><p>Playback events: {playback.length}</p>{playback.length > 0 && <ul aria-label={`Playback times for item ${detail.position}`}>{playback.map((event, index) => <li key={`${event.mediaId}-${event.playedAt}-${index}`}>Played: {event.playedAt}</li>)}</ul>}</article>; })}</section>
    </>}
  </section>;
}
