import type { Actor } from "@/features/identity/domain/contracts";
import { SignOutButton } from "@/features/identity/ui/sign-out-button";
import type { LearnerHome as LearnerHomeData } from "../domain/contracts";

const duration = (seconds: number) => `${Math.round(seconds / 60)} minutes`;
export function LearnerHome({ actor, home, notice }: { actor: Actor; home: LearnerHomeData; notice?: string }) {
  const recommendationSets = home.recommendation?.setIds.flatMap((id) => home.allSets.filter((set) => set.id === id)) ?? [];
  return <main className="shell"><section className="learner-home"><div className="home-heading"><div><p className="eyebrow">Signed in as {actor.displayName}</p><h1>Your practice</h1></div><SignOutButton accountId={actor.id} /></div>{notice && <p className="notice" role="status">{notice}</p>}<section aria-labelledby="recommendations"><h2 id="recommendations">Recommended for you</h2>{home.recommendation ? <><p role="status">These activities support your practice area: {home.recommendation.practiceArea}.</p><ol className="recommendation-list">{recommendationSets.map((set) => <li key={set.id}>{set.title}</li>)}</ol></> : <p role="status">Choose any practice activity to get started. Recommendations will appear when there is enough recent practice.</p>}</section><section aria-labelledby="browse-practice"><h2 id="browse-practice">Browse practice</h2><form className="practice-filters"><label>Topic<select name="topic" defaultValue={home.filters.topic ?? ""}><option value="">All topics</option>{home.filters.topics.map((topic) => <option key={topic}>{topic}</option>)}</select></label><label>Task type<select name="taskType" defaultValue={home.filters.taskType ?? ""}><option value="">All task types</option>{home.filters.taskTypes.map((taskType) => <option key={taskType}>{taskType}</option>)}</select></label><button type="submit">Apply filters</button></form><section aria-label="Published practice activities" className="practice-list">{home.sets.map((set) => <article className="practice-card" key={set.id}><p className="eyebrow">{set.topic}</p><h3>{set.title}</h3><p>{set.taskType} · {set.paper === "listening" ? "Listening" : "Reading and Writing"} Part {set.part} · {duration(set.estimatedDurationSeconds)}</p>{set.lastSavedAt && <p>Last saved {set.lastSavedAt.toLocaleString("en-GB")}</p>}<a className="practice-action" href={set.action === "Review" && set.submittedAttemptId ? `/learner/practice/${set.id}/attempt/${set.submittedAttemptId}/review` : `/learner/practice/${set.id}`}>{set.action}</a></article>)}{!home.sets.length && <p>No published practice activities match these filters.</p>}</section></section></section></main>;
}
