import { database } from "@/infrastructure/database/client";
import { authorise, IdentityError } from "@/features/identity/application/auth";
import type { Actor } from "@/features/identity/domain/contracts";
import { serverConfig } from "@/shared/config/server";
import { findingsFrom, generatedMediaOutputSchema, generatedQuestionOutputSchema, generationRequestSchema, mediaDraftSchema, questionDraftSchema, type GenerationRequest, type MediaDraftInput, type QuestionDraftInput } from "../domain/contracts";
import { generatedProvenance, outputHash } from "../domain/provenance";
import { GatewayError, generate } from "../infrastructure/gateways";
import * as repository from "../infrastructure/repositories";
// eslint-disable-next-line no-unused-vars
export class ContentError extends Error { constructor(readonly code: string, message: string, readonly findings: { field: string; code: string; message: string }[] = []) { super(message); } }
const staff = (actor: Actor) => authorise(actor, ["academic_lead", "admin"]);
// eslint-disable-next-line no-unused-vars
const parse = <T>(schema: { safeParse: (input: unknown) => { success: true; data: T } | { success: false; error: Parameters<typeof findingsFrom>[0] } }, input: unknown): T => { const result = schema.safeParse(input); if (!result.success) throw new ContentError("VALIDATION_FAILED", "Check the named validation findings.", findingsFrom(result.error)); return result.data; };
export async function getContentDrafts(actor: Actor) { staff(actor); return repository.listDrafts(); }
async function validateReferences(input: QuestionDraftInput | MediaDraftInput, tx: Parameters<Parameters<typeof database.transaction>[0]>[0]) { const refs = await repository.getControlledReferences(input, tx); const requested = [input.primaryTargetId, ...input.supportingTargetIds, ...input.topicIds]; const findings = requested.filter((id) => !refs.targets.some((target) => target.id === id && target.isApproved)).map((id) => ({ field: "targetIds", code: "TARGET_NOT_CONTROLLED", message: `The selected target ${id} is not approved for controlled use.` })); if (!refs.guidance) findings.push({ field: "guidanceId", code: "GUIDANCE_NOT_FOUND", message: "The selected controlled guidance was not found." }); else if (refs.guidance.paper !== input.paper || refs.guidance.part !== input.part || refs.guidance.engine !== input.engine) findings.push({ field: "guidanceId", code: "GUIDANCE_SCOPE_MISMATCH", message: "The selected guidance does not match the draft paper, part and engine." }); if ("answerPolicyVersionId" in input && (!refs.policy || refs.policy.policy.targetId !== input.primaryTargetId || refs.policy.policy.guidanceId !== input.guidanceId || refs.policy.policy.paper !== input.paper || refs.policy.policy.part !== input.part || refs.policy.policy.engine !== input.engine)) findings.push({ field: "answerPolicyVersionId", code: "ANSWER_POLICY_SCOPE_MISMATCH", message: "The selected answer-policy version does not match this draft." }); if (findings.length) throw new ContentError("VALIDATION_FAILED", "Check the named validation findings.", findings); }
export async function createManualQuestion(actor: Actor, input: QuestionDraftInput) { staff(actor); const valid = parse(questionDraftSchema, input); return database.transaction(async (tx) => { await validateReferences(valid, tx); return repository.createQuestion(valid, actor.id, "manual", tx); }); }
export async function createManualMedia(actor: Actor, input: MediaDraftInput) { staff(actor); const valid = parse(mediaDraftSchema, input); return database.transaction(async (tx) => { await validateReferences(valid, tx); return repository.createMedia(valid, actor.id, "manual", tx); }); }
export async function reviseQuestion(actor: Actor, sourceId: string, input: QuestionDraftInput) { staff(actor); const valid = parse(questionDraftSchema, input); return database.transaction(async (tx) => { if (!await repository.getQuestion(sourceId, tx)) throw new ContentError("QUESTION_DRAFT_NOT_FOUND", "The question draft was not found."); await validateReferences(valid, tx); return repository.createQuestion(valid, actor.id, "manual", tx, sourceId); }); }
export async function reviseMedia(actor: Actor, sourceId: string, input: MediaDraftInput) { staff(actor); const valid = parse(mediaDraftSchema, input); return database.transaction(async (tx) => { if (!await repository.getMedia(sourceId, tx)) throw new ContentError("MEDIA_DRAFT_NOT_FOUND", "The media draft was not found."); await validateReferences(valid, tx); return repository.createMedia(valid, actor.id, "manual", tx, sourceId); }); }
export async function requestAiDraft(actor: Actor, input: GenerationRequest, sourceId?: string) {
  staff(actor); const request = parse(generationRequestSchema, input); const kind = request.kind === "text" ? "question" : "media";
  if (!serverConfig.AI_DRAFT_PROVIDER_GATE_CLOSED) { await database.transaction((tx) => repository.recordAudit("AI_DRAFT_REQUEST_BLOCKED_GATE_OPEN", kind, request.draft.primaryTargetId, actor.id, tx)); throw new ContentError("AI_DRAFT_PROVIDER_GATE_OPEN", "AI draft generation is unavailable until the provider gate is closed."); }
  try {
    await database.transaction(async (tx) => { await validateReferences(request.draft, tx); if (sourceId) { const exists = request.kind === "text" ? await repository.getQuestion(sourceId, tx) : await repository.getMedia(sourceId, tx); if (!exists) throw new ContentError("CONTENT_DRAFT_NOT_FOUND", "The source draft was not found."); } });
    let result; try { result = await generate(request); } catch (error) { if (error instanceof GatewayError) throw new ContentError(error.code, error.message); throw error; }
    const output = "answerPolicyVersionId" in request.draft ? parse(generatedQuestionOutputSchema, result.output) : parse(generatedMediaOutputSchema, result.output);
    return await database.transaction(async (tx) => { if (request.kind === "text") { const generated = { ...request.draft, ...output as { prompt: string; options: string[] }, provenance: generatedProvenance(request, result.endpoint, result.model) }; await validateReferences(generated, tx); const targetId = await repository.createQuestion(generated, actor.id, "generated", tx, sourceId); await repository.recordGeneration(kind, targetId, request.kind, result.endpoint, result.model, { staffPrompt: request.staffPrompt }, request.permittedReferences, outputHash(result.output), tx); await repository.recordAudit("AI_DRAFT_REQUEST_SUCCEEDED", kind, targetId, actor.id, tx); return targetId; } const generated = { ...request.draft, ...output as { description: string; previewUrl?: string }, provenance: generatedProvenance(request, result.endpoint, result.model) }; await validateReferences(generated, tx); const targetId = await repository.createMedia(generated, actor.id, "generated", tx, sourceId); await repository.recordGeneration(kind, targetId, request.kind, result.endpoint, result.model, { staffPrompt: request.staffPrompt }, request.permittedReferences, outputHash(result.output), tx); await repository.recordAudit("AI_DRAFT_REQUEST_SUCCEEDED", kind, targetId, actor.id, tx); return targetId; });
  } catch (error) {
    try { await database.transaction((tx) => repository.recordAudit("AI_DRAFT_REQUEST_FAILED", kind, request.draft.primaryTargetId, actor.id, tx)); } catch { /* Preserve the original downstream failure if independent audit persistence also fails. */ }
    throw error;
  }
}
export { IdentityError };
