import { database } from "@/infrastructure/database/client";
import { authorise, IdentityError } from "@/features/identity/application/auth";
import type { Actor } from "@/features/identity/domain/contracts";
import { validateVectors } from "../domain/answer-policy";
import { findingsFrom, guidanceSchema, policyVersionSchema, targetSchema, type GuidanceInput, type PolicyVersionInput, type TargetInput } from "../domain/contracts";
import * as repository from "../infrastructure/repositories";
export class CurriculumError extends Error { readonly code: string; readonly findings: { field: string; code: string; message: string }[]; constructor(code: string, message: string, findings: { field: string; code: string; message: string }[] = []) { super(message); this.code = code; this.findings = findings; } }
const staff = (actor: Actor) => authorise(actor, ["academic_lead", "admin"]);
// eslint-disable-next-line no-unused-vars
const parse = <T>(schema: { safeParse: (value: unknown) => { success: true; data: T } | { success: false; error: Parameters<typeof findingsFrom>[0] } }, input: unknown): T => { const result = schema.safeParse(input); if (!result.success) throw new CurriculumError("VALIDATION_FAILED", "Check the named validation findings.", findingsFrom(result.error)); return result.data; };
const databaseFailure = (error: unknown, conflict: string, message: string) => { if (error instanceof CurriculumError || error instanceof IdentityError) throw error; if (error instanceof Error && /(unique|duplicate|23505)/i.test(error.message)) throw new CurriculumError(conflict, message); throw error; };
export async function getCatalogue(actor: Actor) { staff(actor); return repository.listCatalogue(); }
export async function createCurriculumTarget(actor: Actor, input: TargetInput) { staff(actor); const valid = parse(targetSchema, input); try { return await database.transaction((tx) => repository.createTarget(valid, actor.id, tx)); } catch (error) { databaseFailure(error, "TARGET_ID_CONFLICT", "That canonical target identifier already exists."); } }
export async function createCurriculumGuidance(actor: Actor, input: GuidanceInput) { staff(actor); const valid = parse(guidanceSchema, input); try { return await database.transaction((tx) => repository.createGuidance(valid, actor.id, tx)); } catch (error) { databaseFailure(error, "GUIDANCE_CONFLICT", "That guidance record already exists."); } }
export async function updateCurriculumTarget(actor: Actor, id: string, input: Omit<TargetInput, "canonicalId">) { staff(actor); const valid = parse(targetSchema.omit({ canonicalId: true }), input); if (!await database.transaction((tx) => repository.updateTarget(id, valid, actor.id, tx))) throw new CurriculumError("TARGET_NOT_FOUND", "The curriculum target was not found."); }
export async function updateCurriculumGuidance(actor: Actor, id: string, input: GuidanceInput) { staff(actor); const valid = parse(guidanceSchema, input); if (!await database.transaction((tx) => repository.updateGuidance(id, valid, actor.id, tx))) throw new CurriculumError("GUIDANCE_NOT_FOUND", "The internal guidance record was not found."); }
export async function createAnswerPolicyVersion(actor: Actor, input: PolicyVersionInput) {
  staff(actor); const valid = parse(policyVersionSchema, input); const findings = validateVectors(valid); if (findings.length) throw new CurriculumError("CONFORMANCE_VECTOR_CONFLICT", findings[0]!.message, findings);
  try { return await database.transaction(async (tx) => {
    const target = await repository.getTarget(valid.targetId, tx); if (!target) throw new CurriculumError("TARGET_NOT_FOUND", "The selected curriculum target was not found.");
    const guidance = await repository.getGuidance(valid.guidanceId, tx); if (!guidance) throw new CurriculumError("GUIDANCE_NOT_FOUND", "The selected controlled guidance was not found."); if (guidance.paper !== valid.paper || guidance.part !== valid.part || guidance.engine !== valid.engine) throw new CurriculumError("GUIDANCE_SCOPE_MISMATCH", "The selected guidance does not match the policy paper, part and engine.");
    const approvedNames = new Set((guidance.approvedNames as string[]).map((name) => name.toLocaleLowerCase("en-GB"))); const approvedNumbers = new Set(guidance.approvedNumbers as number[]); const values = [valid.canonicalAnswer, ...valid.acceptedAnswers]; const fieldFindings = values.flatMap((value, index) => valid.inputKind === "name" && (!approvedNames.has(String(value).toLocaleLowerCase("en-GB"))) ? [{ field: `answers.${index}`, code: "NAME_NOT_APPROVED", message: "The name is outside controlled guidance." }] : valid.inputKind === "number" && (!approvedNumbers.has(Number(value))) ? [{ field: `answers.${index}`, code: "NUMBER_NOT_APPROVED", message: "The number is outside controlled guidance." }] : []); if ((target.category === "vocabulary" || target.category === "grammar") && !target.isApproved) fieldFindings.push({ field: "targetId", code: `${target.category.toUpperCase()}_NOT_CONTROLLED`, message: "The selected target is not approved for controlled use." }); if (valid.maxWords > guidance.maxWords) fieldFindings.push({ field: "maxWords", code: "TEMPLATE_MAX_WORDS_EXCEEDED", message: "The policy maximum words exceeds selected task guidance." }); if (fieldFindings.length) throw new CurriculumError("VALIDATION_FAILED", "Check the named validation findings.", fieldFindings);
    if (valid.policyId) { const policy = await repository.getPolicy(valid.policyId, tx); if (!policy) throw new CurriculumError("POLICY_NOT_FOUND", "The answer policy was not found."); if (policy.targetId !== valid.targetId) throw new CurriculumError("POLICY_TARGET_MISMATCH", "A policy version must keep its existing curriculum target."); if (policy.engine !== valid.engine) throw new CurriculumError("POLICY_ENGINE_MISMATCH", "A policy version must keep its existing P0 engine."); if (policy.paper !== valid.paper || policy.part !== valid.part || policy.guidanceId !== valid.guidanceId) throw new CurriculumError("POLICY_SCOPE_MISMATCH", "A policy version must keep its existing controlled guidance scope."); }
    else if (await repository.policyCanonicalExists(valid.canonicalId!, tx)) throw new CurriculumError("POLICY_ID_CONFLICT", "That policy identifier already exists.");
    return repository.createPolicyVersion(valid, actor.id, tx);
  }); } catch (error) { databaseFailure(error, "POLICY_VERSION_CONFLICT", "The policy changed while this version was being saved. Try again."); }
}
export { IdentityError };
