"use server";
import { revalidatePath } from "next/cache";
import { createAnswerPolicyVersion, createCurriculumGuidance, createCurriculumTarget, CurriculumError, updateCurriculumGuidance, updateCurriculumTarget } from "@/features/curriculum/application/curriculum";
import { currentActor } from "@/features/identity/ui/session";
import type { AnswerValue } from "@/features/curriculum/domain/contracts";
export type CurriculumActionState = { error?: { code: string; message: string; findings?: { field: string; code: string; message: string }[] }; success?: string };
const failure = (error: unknown, fallback: string): CurriculumActionState => error instanceof CurriculumError || error instanceof Error && "code" in error ? { error: { code: (error as CurriculumError).code, message: error.message, ...((error instanceof CurriculumError && error.findings.length) ? { findings: error.findings } : {}) } } : { error: { code: fallback, message: "The record could not be saved." } };
const actorFor = async () => { const actor = await currentActor(); if (!actor) throw new CurriculumError("FORBIDDEN", "You do not have access to that page."); return actor; };
export async function createTargetAction(_: CurriculumActionState, formData: FormData): Promise<CurriculumActionState> { try { await createCurriculumTarget(await actorFor(), { canonicalId: String(formData.get("canonicalId") ?? ""), category: String(formData.get("category") ?? "") as "vocabulary", guidance: String(formData.get("guidance") ?? ""), isApproved: formData.get("isApproved") === "on" }); revalidatePath("/academic-lead"); return { success: "Curriculum target saved." }; } catch (error) { return failure(error, "TARGET_SAVE_FAILED"); } }
export async function updateTargetAction(_: CurriculumActionState, formData: FormData): Promise<CurriculumActionState> { try { await updateCurriculumTarget(await actorFor(), String(formData.get("targetId")), { category: String(formData.get("category")) as "vocabulary", guidance: String(formData.get("guidance")), isApproved: formData.get("isApproved") === "on" }); revalidatePath("/academic-lead"); return { success: "Curriculum target updated." }; } catch (error) { return failure(error, "TARGET_UPDATE_FAILED"); } }
export async function createGuidanceAction(_: CurriculumActionState, formData: FormData): Promise<CurriculumActionState> { try { await createCurriculumGuidance(await actorFor(), { paper: String(formData.get("paper")) as "listening", part: Number(formData.get("part")), engine: String(formData.get("engine")) as "picture_true_false", topic: String(formData.get("topic")), taskFormat: String(formData.get("taskFormat")), maxWords: Number(formData.get("maxWords")), maxOptions: Number(formData.get("maxOptions")), approvedNames: String(formData.get("approvedNames") ?? "").split(",").map((value) => value.trim()).filter(Boolean), approvedNumbers: String(formData.get("approvedNumbers") ?? "").split(",").filter(Boolean).map(Number) }); revalidatePath("/academic-lead"); return { success: "Internal guidance saved." }; } catch (error) { return failure(error, "GUIDANCE_SAVE_FAILED"); } }
export async function updateGuidanceAction(_: CurriculumActionState, formData: FormData): Promise<CurriculumActionState> { try { await updateCurriculumGuidance(await actorFor(), String(formData.get("guidanceId")), { paper: String(formData.get("paper")) as "listening", part: Number(formData.get("part")), engine: String(formData.get("engine")) as "picture_true_false", topic: String(formData.get("topic")), taskFormat: String(formData.get("taskFormat")), maxWords: Number(formData.get("maxWords")), maxOptions: Number(formData.get("maxOptions")), approvedNames: String(formData.get("approvedNames") ?? "").split(",").map((value) => value.trim()).filter(Boolean), approvedNumbers: String(formData.get("approvedNumbers") ?? "").split(",").filter(Boolean).map(Number) }); revalidatePath("/academic-lead"); return { success: "Internal guidance updated." }; } catch (error) { return failure(error, "GUIDANCE_UPDATE_FAILED"); } }
const parseValue = (raw: string, kind: string): AnswerValue => { if (kind === "boolean") { if (raw !== "true" && raw !== "false") throw new CurriculumError("VALIDATION_FAILED", "Check the named validation findings.", [{ field: "answer", code: "BOOLEAN_VALUE_INVALID", message: "Use true or false." }]); return raw === "true"; } if (kind === "number") { if (!/^(?:0|[1-9][0-9]*)$/.test(raw)) throw new CurriculumError("VALIDATION_FAILED", "Check the named validation findings.", [{ field: "answer", code: "NUMBER_VALUE_INVALID", message: "Use a whole number." }]); return Number(raw); } return kind === "assignment" ? JSON.parse(raw) as Record<string, string> : raw; };
const parseVectorValue = (raw: string, kind: string): AnswerValue => kind === "number" && /[a-z]/i.test(raw) ? raw : parseValue(raw, kind);
export async function createPolicyAction(_: CurriculumActionState, formData: FormData): Promise<CurriculumActionState> { try { const inputKind = String(formData.get("inputKind")); const policyId = String(formData.get("policyId") ?? ""); const canonicalAnswer = parseValue(String(formData.get("canonicalAnswer") ?? ""), inputKind); const vectors = ["correct", "incorrect", "needs_teacher_review"].map((expectedOutcome) => ({ response: parseVectorValue(String(formData.get(`vector-${expectedOutcome}`) ?? ""), inputKind), expectedOutcome: expectedOutcome as "correct" })); await createAnswerPolicyVersion(await actorFor(), { ...(policyId ? { policyId } : { canonicalId: String(formData.get("canonicalId") ?? "") }), targetId: String(formData.get("targetId") ?? ""), guidanceId: String(formData.get("guidanceId") ?? ""), paper: String(formData.get("paper")) as "listening", part: Number(formData.get("part")), engine: String(formData.get("engine")) as "picture_true_false", inputKind: inputKind as "boolean", canonicalAnswer, acceptedAnswers: String(formData.get("acceptedAnswers") ?? "").split("\n").map((value) => value.trim()).filter(Boolean).map((value) => parseValue(value, inputKind)), normalisation: { unicode: "NFC", locale: "en-GB", caseSensitive: false, trimWhitespace: true, normalizePunctuation: true, normalizeNumberForms: inputKind === "number" }, maxWords: Number(formData.get("maxWords")), teacherReviewIfUncertain: formData.get("teacherReviewIfUncertain") === "on", vectors }); revalidatePath("/academic-lead"); return { success: "A new immutable answer-policy version was saved." }; } catch (error) { return failure(error, "POLICY_SAVE_FAILED"); } }
