import { beforeEach, describe, expect, it, vi } from "vitest";
const dependencies = vi.hoisted(() => ({ transaction: vi.fn(), createQuestion: vi.fn(), createMedia: vi.fn(), getQuestion: vi.fn(), getMedia: vi.fn(), getControlledReferences: vi.fn(), recordGeneration: vi.fn(), recordAudit: vi.fn(), generate: vi.fn() }));
const config = vi.hoisted(() => ({ AI_DRAFT_PROVIDER_GATE_CLOSED: false }));
vi.mock("@/infrastructure/database/client", () => ({ database: { transaction: dependencies.transaction } }));
vi.mock("@/features/content/infrastructure/repositories", () => dependencies);
vi.mock("@/features/content/infrastructure/gateways", () => ({ GatewayError: class GatewayError extends Error { constructor(code: string, message: string) { super(message); Object.assign(this, { code }); } }, generate: dependencies.generate }));
vi.mock("@/shared/config/server", () => ({ serverConfig: config }));
import { createManualQuestion, requestAiDraft, reviseQuestion } from "@/features/content/application/content";
const lead = { id: "018f0000-0000-7000-8000-000000000001", email: "lead@example.test", displayName: "Lead", role: "academic_lead" as const };
const teacher = { ...lead, role: "teacher" as const };
const input = { paper: "reading_writing" as const, part: 1, engine: "picture_true_false" as const, primaryTargetId: "018f0000-0000-7000-8000-000000000002", supportingTargetIds: [], topicIds: ["018f0000-0000-7000-8000-000000000003"], guidanceId: "018f0000-0000-7000-8000-000000000004", answerPolicyVersionId: "018f0000-0000-7000-8000-000000000005", prompt: "This is a cat.", options: ["true", "false"], estimatedDurationSeconds: 60, accessibilityMetadata: { altText: "A cat" }, provenance: { source: "Original staff writing", rightsReference: "Centre-owned" } };
describe("content draft use cases", () => {
  // The callback parameter documents the transaction boundary supplied to use cases.
  // eslint-disable-next-line no-unused-vars
  beforeEach(() => { vi.clearAllMocks(); config.AI_DRAFT_PROVIDER_GATE_CLOSED = false; dependencies.transaction.mockImplementation(async (boundary: (transaction: object) => unknown) => boundary({ transaction: "boundary" })); dependencies.getControlledReferences.mockResolvedValue({ targets: [{ id: input.primaryTargetId, isApproved: true }, { id: input.topicIds[0], isApproved: true }], guidance: { paper: input.paper, part: input.part, engine: input.engine }, policy: { policy: { targetId: input.primaryTargetId, guidanceId: input.guidanceId, paper: input.paper, part: input.part, engine: input.engine } } }); });
  it("stores an authorised manual draft in a transaction", async () => { await createManualQuestion(lead, input); expect(dependencies.createQuestion).toHaveBeenCalledWith(input, lead.id, "manual", { transaction: "boundary" }); });
  it("denies a teacher before any content or audit mutation", async () => { await expect(createManualQuestion(teacher, input)).rejects.toMatchObject({ code: "FORBIDDEN" }); expect(dependencies.transaction).not.toHaveBeenCalled(); });
  it("blocks an open AI provider gate without gateway or generated draft", async () => { await expect(requestAiDraft(lead, { kind: "text", staffPrompt: "Create a simple draft", permittedReferences: [], draft: input })).rejects.toMatchObject({ code: "AI_DRAFT_PROVIDER_GATE_OPEN" }); expect(dependencies.generate).not.toHaveBeenCalled(); expect(dependencies.createQuestion).not.toHaveBeenCalled(); });
  it("validates controlled references before sending an AI payload", async () => { config.AI_DRAFT_PROVIDER_GATE_CLOSED = true; dependencies.getControlledReferences.mockResolvedValue({ targets: [], guidance: undefined, policy: undefined }); await expect(requestAiDraft(lead, { kind: "text", staffPrompt: "Create a simple draft", permittedReferences: [], draft: input })).rejects.toMatchObject({ code: "VALIDATION_FAILED" }); expect(dependencies.generate).not.toHaveBeenCalled(); });
  it("incorporates gateway output and records provenance with a SHA-256 hash", async () => { config.AI_DRAFT_PROVIDER_GATE_CLOSED = true; dependencies.generate.mockResolvedValue({ endpoint: "https://ai.example.test", model: "text-model", output: { prompt: "Generated cat prompt", options: ["true", "false"] } }); dependencies.createQuestion.mockResolvedValue("018f0000-0000-7000-8000-000000000006"); await requestAiDraft(lead, { kind: "text", staffPrompt: "Create a simple draft", permittedReferences: [{ id: "ref-1", description: "Original reference" }], draft: input }); expect(dependencies.createQuestion).toHaveBeenCalledWith(expect.objectContaining({ prompt: "Generated cat prompt", options: ["true", "false"], provenance: expect.objectContaining({ gatewayKind: "text", model: "text-model" }) }), lead.id, "generated", { transaction: "boundary" }, undefined); expect(dependencies.recordGeneration).toHaveBeenCalledWith("question", expect.any(String), "text", "https://ai.example.test", "text-model", { staffPrompt: "Create a simple draft" }, [{ id: "ref-1", description: "Original reference" }], expect.stringMatching(/^[a-f0-9]{64}$/), { transaction: "boundary" }); });
  it("returns named controlled-reference findings without persisting a partial draft", async () => { dependencies.getControlledReferences.mockResolvedValue({ targets: [], guidance: undefined, policy: undefined }); await expect(createManualQuestion(lead, input)).rejects.toMatchObject({ code: "VALIDATION_FAILED", findings: expect.arrayContaining([expect.objectContaining({ code: "TARGET_NOT_CONTROLLED" }), expect.objectContaining({ code: "GUIDANCE_NOT_FOUND" })]) }); expect(dependencies.createQuestion).not.toHaveBeenCalled(); });
  it("creates a new manual version instead of replacing a source draft", async () => { dependencies.getQuestion.mockResolvedValue({ id: "018f0000-0000-7000-8000-000000000007" }); await reviseQuestion(lead, "018f0000-0000-7000-8000-000000000007", input); expect(dependencies.createQuestion).toHaveBeenCalledWith(input, lead.id, "manual", { transaction: "boundary" }, "018f0000-0000-7000-8000-000000000007"); });
});
