import { beforeEach, describe, expect, it, vi } from "vitest";
const dependencies = vi.hoisted(() => ({ transaction: vi.fn(), createTarget: vi.fn(), createGuidance: vi.fn(), updateTarget: vi.fn(), updateGuidance: vi.fn(), getTarget: vi.fn(), getGuidance: vi.fn(), getPolicy: vi.fn(), policyCanonicalExists: vi.fn(), createPolicyVersion: vi.fn() }));
vi.mock("@/infrastructure/database/client", () => ({ database: { transaction: dependencies.transaction } }));
vi.mock("@/features/curriculum/infrastructure/repositories", () => dependencies);
import { createAnswerPolicyVersion, createCurriculumGuidance, createCurriculumTarget, updateCurriculumTarget } from "@/features/curriculum/application/curriculum";
const lead = { id: "018f0000-0000-7000-8000-000000000001", email: "lead@example.test", displayName: "Lead", role: "academic_lead" as const };
const teacher = { ...lead, role: "teacher" as const };
const targetId = "018f0000-0000-7000-8000-000000000002";
const guidanceId = "018f0000-0000-7000-8000-000000000003";
const policy = { canonicalId: "true-false", targetId, guidanceId, paper: "reading_writing" as const, part: 1, engine: "picture_true_false" as const, inputKind: "boolean" as const, canonicalAnswer: true, acceptedAnswers: [], normalisation: { unicode: "NFC" as const, locale: "en-GB" as const, caseSensitive: false, trimWhitespace: true, normalizePunctuation: true, normalizeNumberForms: false }, maxWords: 1, teacherReviewIfUncertain: true, vectors: [{ response: true, expectedOutcome: "correct" as const }, { response: false, expectedOutcome: "incorrect" as const }, { response: "wrong", expectedOutcome: "needs_teacher_review" as const }] };
describe("curriculum use cases", () => {
  // eslint-disable-next-line no-unused-vars
  beforeEach(() => { vi.clearAllMocks(); dependencies.transaction.mockImplementation(async (work: (tx: object) => unknown) => work({ transaction: "boundary" })); dependencies.getTarget.mockResolvedValue({ id: targetId, category: "vocabulary", guidance: "Controlled vocabulary", isApproved: true }); dependencies.getGuidance.mockResolvedValue({ id: guidanceId, paper: "reading_writing", part: 1, engine: "picture_true_false", approvedNames: ["Sam"], approvedNumbers: [1, 2], maxWords: 1 }); dependencies.policyCanonicalExists.mockResolvedValue(false); dependencies.getPolicy.mockResolvedValue(undefined); });
  it("denies a teacher before a mutation transaction begins", async () => { await expect(createCurriculumTarget(teacher, { canonicalId: "animals", category: "topic", guidance: "Animals", isApproved: false })).rejects.toMatchObject({ code: "FORBIDDEN" }); expect(dependencies.transaction).not.toHaveBeenCalled(); });
  it("creates authorised targets inside one transaction", async () => { await createCurriculumTarget(lead, { canonicalId: "animals", category: "topic", guidance: "Animals", isApproved: false }); expect(dependencies.createTarget).toHaveBeenCalledWith({ canonicalId: "animals", category: "topic", guidance: "Animals", isApproved: false }, lead.id, { transaction: "boundary" }); });
  it("only persists a valid policy version after controlled target checks", async () => { await createAnswerPolicyVersion(lead, policy); expect(dependencies.createPolicyVersion).toHaveBeenCalledWith(policy, lead.id, { transaction: "boundary" }); });
  it("rejects a conflicting policy vector before opening a transaction", async () => { await expect(createAnswerPolicyVersion(lead, { ...policy, vectors: [{ response: true, expectedOutcome: "incorrect" }, ...policy.vectors.slice(1)] })).rejects.toMatchObject({ code: "CONFORMANCE_VECTOR_CONFLICT" }); expect(dependencies.createPolicyVersion).not.toHaveBeenCalled(); });
  it("rejects an append that changes its fixed target or engine", async () => { const policyId = "018f0000-0000-7000-8000-000000000004"; dependencies.getPolicy.mockResolvedValue({ id: policyId, targetId, engine: "picture_true_false" }); await expect(createAnswerPolicyVersion(lead, { ...policy, policyId, canonicalId: undefined, targetId: "018f0000-0000-7000-8000-000000000005" })).rejects.toMatchObject({ code: "POLICY_TARGET_MISMATCH" }); dependencies.getGuidance.mockResolvedValue({ id: guidanceId, paper: "reading_writing", part: 1, engine: "picture_yes_no", approvedNames: ["Sam"], approvedNumbers: [1, 2], maxWords: 1 }); await expect(createAnswerPolicyVersion(lead, { ...policy, policyId, canonicalId: undefined, engine: "picture_yes_no", inputKind: "yes_no", canonicalAnswer: "yes", vectors: [{ response: "yes", expectedOutcome: "correct" }, { response: "no", expectedOutcome: "incorrect" }, { response: "not known", expectedOutcome: "needs_teacher_review" }] })).rejects.toMatchObject({ code: "POLICY_ENGINE_MISMATCH" }); });
  it("returns named findings for invalid task guidance without opening a transaction", async () => { await expect(createCurriculumGuidance(lead, { paper: "listening", part: 6, engine: "picture_true_false", topic: "animals", taskFormat: "choice", maxWords: 0, maxOptions: 11, approvedNames: [], approvedNumbers: [21] })).rejects.toMatchObject({ code: "VALIDATION_FAILED", findings: expect.arrayContaining([expect.objectContaining({ field: "part" }), expect.objectContaining({ field: "maxWords" }), expect.objectContaining({ field: "maxOptions" }), expect.objectContaining({ field: "approvedNumbers.0" })]) }); expect(dependencies.createGuidance).not.toHaveBeenCalled(); });
  it("rejects policy values outside the controlled guidance before persistence", async () => { dependencies.getGuidance.mockResolvedValue({ id: guidanceId, paper: "reading_writing", part: 1, engine: "audio_note_taking", approvedNames: ["Sam"], approvedNumbers: [1, 2], maxWords: 1 }); await expect(createAnswerPolicyVersion(lead, { ...policy, engine: "audio_note_taking", inputKind: "name", canonicalAnswer: "Jo", acceptedAnswers: [], vectors: [{ response: "Jo", expectedOutcome: "correct" }, { response: "Sam", expectedOutcome: "incorrect" }, { response: "too many", expectedOutcome: "needs_teacher_review" }] })).rejects.toMatchObject({ code: "VALIDATION_FAILED", findings: [expect.objectContaining({ code: "NAME_NOT_APPROVED" })] }); expect(dependencies.createPolicyVersion).not.toHaveBeenCalled(); });
  it("updates target metadata without accepting a canonical identifier change", async () => { dependencies.updateTarget.mockResolvedValue(true); await updateCurriculumTarget(lead, targetId, { category: "vocabulary", guidance: "Revised controlled guidance", isApproved: true }); expect(dependencies.updateTarget).toHaveBeenCalledWith(targetId, { category: "vocabulary", guidance: "Revised controlled guidance", isApproved: true }, lead.id, { transaction: "boundary" }); });
  it("rejects unapproved vocabulary and grammar targets before policy persistence", async () => { dependencies.getTarget.mockResolvedValue({ id: targetId, category: "vocabulary", guidance: "Draft", isApproved: false }); await expect(createAnswerPolicyVersion(lead, policy)).rejects.toMatchObject({ code: "VALIDATION_FAILED", findings: [expect.objectContaining({ code: "VOCABULARY_NOT_CONTROLLED" })] }); dependencies.getTarget.mockResolvedValue({ id: targetId, category: "grammar", guidance: "Draft", isApproved: false }); await expect(createAnswerPolicyVersion(lead, policy)).rejects.toMatchObject({ code: "VALIDATION_FAILED", findings: [expect.objectContaining({ code: "GRAMMAR_NOT_CONTROLLED" })] }); });
  it("rejects a policy maxWords value beyond the matching task guidance", async () => { await expect(createAnswerPolicyVersion(lead, { ...policy, maxWords: 2 })).rejects.toMatchObject({ code: "VALIDATION_FAILED", findings: [expect.objectContaining({ code: "TEMPLATE_MAX_WORDS_EXCEEDED" })] }); });
  it("uses only the selected guidance record rather than unrelated same-engine guidance", async () => { dependencies.getGuidance.mockResolvedValue({ id: guidanceId, paper: "reading_writing", part: 1, engine: "picture_true_false", approvedNames: ["Sam"], approvedNumbers: [1, 2], maxWords: 2 }); await createAnswerPolicyVersion(lead, { ...policy, maxWords: 2 }); expect(dependencies.getGuidance).toHaveBeenCalledWith(guidanceId, { transaction: "boundary" }); expect(dependencies.createPolicyVersion).toHaveBeenCalled(); });
});
