import { describe, expect, it } from "vitest";
import { evaluateAnswer, normaliseAnswer, validateVectors } from "@/features/curriculum/domain/answer-policy";
import { policyVersionSchema, type PolicyVersionInput } from "@/features/curriculum/domain/contracts";
const base: PolicyVersionInput = { canonicalId: "number-one", targetId: "018f0000-0000-7000-8000-000000000001", guidanceId: "018f0000-0000-7000-8000-000000000002", paper: "listening", part: 2, engine: "audio_note_taking", inputKind: "number", canonicalAnswer: 1, acceptedAnswers: [], normalisation: { unicode: "NFC", locale: "en-GB", caseSensitive: false, trimWhitespace: true, normalizePunctuation: true, normalizeNumberForms: true }, maxWords: 1, teacherReviewIfUncertain: true, vectors: [{ response: 1, expectedOutcome: "correct" }, { response: 2, expectedOutcome: "incorrect" }, { response: "one extra", expectedOutcome: "needs_teacher_review" }] };
describe("answer policy matching", () => {
  it("applies Unicode, British case, whitespace, punctuation and number-form semantics deterministically", () => { expect(normaliseAnswer("  CAFÉ!  ", { ...base, inputKind: "word", normalisation: { ...base.normalisation, normalizeNumberForms: false } })).toBe("café"); expect(evaluateAnswer("one", base)).toBe("correct"); expect(evaluateAnswer(2, base)).toBe("incorrect"); });
  it("permits and verifies controlled textual number-form conformance vectors", () => { const policy = { ...base, vectors: [{ response: "one", expectedOutcome: "correct" as const }, { response: 2, expectedOutcome: "incorrect" as const }, { response: "one extra", expectedOutcome: "needs_teacher_review" as const }] }; expect(policyVersionSchema.safeParse(policy).success).toBe(true); expect(validateVectors(policy)).toEqual([]); });
  it("sends malformed and excessive controlled input to teacher review when configured", () => { expect(evaluateAnswer("one extra", base)).toBe("needs_teacher_review"); expect(evaluateAnswer("1", base)).toBe("needs_teacher_review"); expect(evaluateAnswer("1", { ...base, teacherReviewIfUncertain: false })).toBe("incorrect"); });
  it("blocks a conformance vector whose expected outcome conflicts with matching", () => expect(validateVectors({ ...base, vectors: [{ response: 1, expectedOutcome: "incorrect" }, ...base.vectors.slice(1)] })).toEqual([{ field: "vectors.0.expectedOutcome", code: "CONFORMANCE_VECTOR_CONFLICT", message: "The expected outcome conflicts with deterministic matching." }]));
  it("enforces engine/input-kind and typed answer shapes for every P0 input kind", () => {
    const cases = [["picture_true_false", "boolean", true], ["picture_yes_no", "yes_no", "yes"], ["audio_picture_choice", "choice", "a"], ["audio_note_taking", "number", 1], ["audio_note_taking", "name", "sam"], ["word_bank_cloze", "word", "cat"], ["word_bank_cloze", "assignment", { blank: "cat" }]] as const;
    for (const [engine, inputKind, answer] of cases) { const incorrect = inputKind === "boolean" ? false : inputKind === "number" ? 2 : inputKind === "assignment" ? { blank: "wrong" } : inputKind === "yes_no" ? "no" : "wrong"; expect(policyVersionSchema.safeParse({ ...base, engine, inputKind, canonicalAnswer: answer, vectors: [{ response: answer, expectedOutcome: "correct" }, { response: incorrect, expectedOutcome: "incorrect" }, { response: "too many words", expectedOutcome: "needs_teacher_review" }] }).success).toBe(true); }
    expect(policyVersionSchema.safeParse({ ...base, engine: "picture_true_false", inputKind: "boolean", canonicalAnswer: "true" }).success).toBe(false);
    expect(policyVersionSchema.safeParse({ ...base, policyId: "018f0000-0000-7000-8000-000000000003" }).success).toBe(false);
  });
  it("normalises assignment values recursively and independently of key insertion order", () => { const assignment = { ...base, inputKind: "assignment" as const, canonicalAnswer: { first: " CAFÉ! ", second: "Cat" }, acceptedAnswers: [], normalisation: { ...base.normalisation, normalizeNumberForms: false }, vectors: [{ response: { first: "café", second: "cat" }, expectedOutcome: "correct" }, { response: { first: "dog", second: "cat" }, expectedOutcome: "incorrect" }, { response: "bad", expectedOutcome: "needs_teacher_review" }] }; expect(evaluateAnswer({ second: " CAT ", first: "café!" }, assignment)).toBe("correct"); });
});
